global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: ''
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: true

route:
  receiver: 'email_notifications'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'email_notifications'
    email_configs:
      - to: ''
        send_resolved: true
