# Generated by Django 5.1 on 2024-08-23 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksCategory',
            fields=[
                ('book_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_mail', models.EmailField(max_length=254)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('book_issue_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookName',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=255)),
                ('book_author_name', models.CharField(max_length=255)),
                ('book_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.bookscategory')),
            ],
        ),
        migrations.CreateModel(
            name='BookIssueRecord',
            fields=[
                ('book_issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_issue_approved', models.BooleanField(default=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('is_return_approved', models.BooleanField(default=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('fine', models.IntegerField(blank=True, null=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.bookname')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.user')),
            ],
        ),
    ]
