# Generated by Django 5.1 on 2024-08-23 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooksCategory',
            new_name='Books_Category',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_email_verified',
            new_name='is_email_verfied',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='book_issue_id',
            new_name='user_book_issue_record_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_mail',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Book_Issue_Record',
            fields=[
                ('book_issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_issue_approve', models.BooleanField()),
                ('issue_date', models.DateField(null=True)),
                ('is_return_approve', models.BooleanField()),
                ('return_date', models.DateField(null=True)),
                ('fine', models.IntegerField(null=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.bookname')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_Book_Issue_Record',
            fields=[
                ('user_book_issue_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.book_issue_record')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.user')),
            ],
        ),
        migrations.DeleteModel(
            name='BookIssueRecord',
        ),
    ]
