# Generated by Django 5.1 on 2024-08-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_rename_bookscategory_books_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_book_issue_record_id',
        ),
    ]
