# Generated by Django 5.1 on 2024-08-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_remove_user_user_book_issue_record_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Book_Issue_Record',
        ),
    ]
