# Generated by Django 5.1 on 2024-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_book_issue_record_is_return_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_issue_record',
            name='is_return_applied',
        ),
        migrations.AlterField(
            model_name='book_issue_record',
            name='is_return_approve',
            field=models.BooleanField(default=None),
        ),
    ]
