# Generated by Django 5.1 on 2024-08-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_alter_book_issue_record_is_return_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.IntegerField(null=True),
        ),
    ]
